' FSAE26 suspension skeleton -- 3D sketch wireframe
' Generated by scripts/export_solidworks_skeleton.py from hardpoints_2027_merged.csv
' Frame: iso. Coordinates in metres (the SolidWorks API is always metres).
' Do not hand-edit: change the hardpoint CSV and regenerate.
'
' Tools > Macro > New (save a blank .swp), then in the VBA editor
' File > Import File... > this .bas, then run main() with F5.

Option Explicit

Dim swApp As Object
Dim swModel As Object
Dim swSketchMgr As Object

Sub main()
    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc

    If swModel Is Nothing Then
        MsgBox "Open a part or an assembly first, then run this macro."
        Exit Sub
    End If
    If swModel.GetType <> 1 And swModel.GetType <> 2 Then
        MsgBox "A 3D sketch needs a part or an assembly."
        Exit Sub
    End If

    Set swSketchMgr = swModel.SketchManager

    ' Replace any previous run rather than stacking a second skeleton.
    DeleteSketch "SUSP_FL"
    DeleteSketch "SUSP_FR"
    DeleteSketch "SUSP_RL"
    DeleteSketch "SUSP_RR"

    ' AddToDB keeps SolidWorks from inferring relations and snapping
    ' the endpoints off their CSV coordinates.
    swSketchMgr.AddToDB = True
    swSketchMgr.DisplayWhenAdded = False

    Build_SUSP_FL
    Build_SUSP_FR
    Build_SUSP_RL
    Build_SUSP_RR

    swSketchMgr.AddToDB = False
    swSketchMgr.DisplayWhenAdded = True
    swModel.EditRebuild3
    swModel.ViewZoomtofit2
    MsgBox "Suspension skeleton: 4 sketch(es), 40 line(s)."
End Sub

Private Sub DeleteSketch(sketchName As String)
    swModel.ClearSelection2 True
    If swModel.Extension.SelectByID2(sketchName, "SKETCH", 0, 0, 0, False, 0, Nothing, 0) Then
        swModel.EditDelete
    End If
    swModel.ClearSelection2 True
End Sub

Private Sub Build_SUSP_FL()
    Dim swFeat As Object
    swModel.ClearSelection2 True
    swSketchMgr.Insert3DSketch True
    ' FL UCA - front leg
    swSketchMgr.CreateLine 0.12, 0.21, 0.321661, -0.012283, 0.536966, 0.3854
    ' FL UCA - rear leg
    swSketchMgr.CreateLine -0.12, 0.21, 0.310356, -0.012283, 0.536966, 0.3854
    ' FL LCA - front leg
    swSketchMgr.CreateLine 0.13, 0.175, 0.117383, 0.010061, 0.582, 0.13
    ' FL LCA - rear leg
    swSketchMgr.CreateLine -0.13, 0.175, 0.117383, 0.010061, 0.582, 0.13
    ' FL Tie Rod - rod
    swSketchMgr.CreateLine -0.03, 0.27, 0.157392, 0.084591, 0.590294, 0.17875
    ' FL Upright - kingpin axis
    swSketchMgr.CreateLine 0.010061, 0.582, 0.13, -0.012283, 0.536966, 0.3854
    ' FL Upright - lower spindle arm
    swSketchMgr.CreateLine 0.010061, 0.582, 0.13, 0, 0.613584, 0.245
    ' FL Upright - upper spindle arm
    swSketchMgr.CreateLine -0.012283, 0.536966, 0.3854, 0, 0.613584, 0.245
    ' FL Upright - steering arm
    swSketchMgr.CreateLine 0.010061, 0.582, 0.13, 0.084591, 0.590294, 0.17875
    ' FL Wheel - loaded radius
    swSketchMgr.CreateLine 0, 0.613584, 0.245, 0, 0.62, 0
    swSketchMgr.Insert3DSketch True
    Set swFeat = swModel.FeatureByPositionReverse(0)
    If Not swFeat Is Nothing Then swFeat.Name = "SUSP_FL"
End Sub

Private Sub Build_SUSP_FR()
    Dim swFeat As Object
    swModel.ClearSelection2 True
    swSketchMgr.Insert3DSketch True
    ' FR UCA - front leg
    swSketchMgr.CreateLine 0.12, -0.21, 0.321661, -0.012283, -0.536966, 0.3854
    ' FR UCA - rear leg
    swSketchMgr.CreateLine -0.12, -0.21, 0.310356, -0.012283, -0.536966, 0.3854
    ' FR LCA - front leg
    swSketchMgr.CreateLine 0.13, -0.175, 0.117383, 0.010061, -0.582, 0.13
    ' FR LCA - rear leg
    swSketchMgr.CreateLine -0.13, -0.175, 0.117383, 0.010061, -0.582, 0.13
    ' FR Tie Rod - rod
    swSketchMgr.CreateLine -0.03, -0.27, 0.157392, 0.084591, -0.590294, 0.17875
    ' FR Upright - kingpin axis
    swSketchMgr.CreateLine 0.010061, -0.582, 0.13, -0.012283, -0.536966, 0.3854
    ' FR Upright - lower spindle arm
    swSketchMgr.CreateLine 0.010061, -0.582, 0.13, 0, -0.613584, 0.245
    ' FR Upright - upper spindle arm
    swSketchMgr.CreateLine -0.012283, -0.536966, 0.3854, 0, -0.613584, 0.245
    ' FR Upright - steering arm
    swSketchMgr.CreateLine 0.010061, -0.582, 0.13, 0.084591, -0.590294, 0.17875
    ' FR Wheel - loaded radius
    swSketchMgr.CreateLine 0, -0.613584, 0.245, 0, -0.62, 0
    swSketchMgr.Insert3DSketch True
    Set swFeat = swModel.FeatureByPositionReverse(0)
    If Not swFeat Is Nothing Then swFeat.Name = "SUSP_FR"
End Sub

Private Sub Build_SUSP_RL()
    Dim swFeat As Object
    swModel.ClearSelection2 True
    swSketchMgr.Insert3DSketch True
    ' RL UCA - front leg
    swSketchMgr.CreateLine -1.3, 0.21, 0.328854, -1.54, 0.519692, 0.390339
    ' RL UCA - rear leg
    swSketchMgr.CreateLine -1.46, 0.21, 0.328854, -1.54, 0.519692, 0.390339
    ' RL LCA - front leg
    swSketchMgr.CreateLine -1.24, 0.175, 0.129529, -1.54, 0.5586, 0.13
    ' RL LCA - rear leg
    swSketchMgr.CreateLine -1.44, 0.175, 0.129529, -1.54, 0.5586, 0.13
    ' RL Tie Rod - rod
    swSketchMgr.CreateLine -1.44, 0.175, 0.169, -1.5946, 0.52081, 0.18353
    ' RL Upright - kingpin axis
    swSketchMgr.CreateLine -1.54, 0.5586, 0.13, -1.54, 0.519692, 0.390339
    ' RL Upright - lower spindle arm
    swSketchMgr.CreateLine -1.54, 0.5586, 0.13, -1.54, 0.593584, 0.245
    ' RL Upright - upper spindle arm
    swSketchMgr.CreateLine -1.54, 0.519692, 0.390339, -1.54, 0.593584, 0.245
    ' RL Upright - steering arm
    swSketchMgr.CreateLine -1.54, 0.5586, 0.13, -1.5946, 0.52081, 0.18353
    ' RL Wheel - loaded radius
    swSketchMgr.CreateLine -1.54, 0.593584, 0.245, -1.54, 0.6, 0
    swSketchMgr.Insert3DSketch True
    Set swFeat = swModel.FeatureByPositionReverse(0)
    If Not swFeat Is Nothing Then swFeat.Name = "SUSP_RL"
End Sub

Private Sub Build_SUSP_RR()
    Dim swFeat As Object
    swModel.ClearSelection2 True
    swSketchMgr.Insert3DSketch True
    ' RR UCA - front leg
    swSketchMgr.CreateLine -1.3, -0.21, 0.328854, -1.54, -0.519692, 0.390339
    ' RR UCA - rear leg
    swSketchMgr.CreateLine -1.46, -0.21, 0.328854, -1.54, -0.519692, 0.390339
    ' RR LCA - front leg
    swSketchMgr.CreateLine -1.24, -0.175, 0.129529, -1.54, -0.5586, 0.13
    ' RR LCA - rear leg
    swSketchMgr.CreateLine -1.44, -0.175, 0.129529, -1.54, -0.5586, 0.13
    ' RR Tie Rod - rod
    swSketchMgr.CreateLine -1.44, -0.175, 0.169, -1.5946, -0.52081, 0.18353
    ' RR Upright - kingpin axis
    swSketchMgr.CreateLine -1.54, -0.5586, 0.13, -1.54, -0.519692, 0.390339
    ' RR Upright - lower spindle arm
    swSketchMgr.CreateLine -1.54, -0.5586, 0.13, -1.54, -0.593584, 0.245
    ' RR Upright - upper spindle arm
    swSketchMgr.CreateLine -1.54, -0.519692, 0.390339, -1.54, -0.593584, 0.245
    ' RR Upright - steering arm
    swSketchMgr.CreateLine -1.54, -0.5586, 0.13, -1.5946, -0.52081, 0.18353
    ' RR Wheel - loaded radius
    swSketchMgr.CreateLine -1.54, -0.593584, 0.245, -1.54, -0.6, 0
    swSketchMgr.Insert3DSketch True
    Set swFeat = swModel.FeatureByPositionReverse(0)
    If Not swFeat Is Nothing Then swFeat.Name = "SUSP_RR"
End Sub
