"""Create the FSAE26 suspension geometry in the active MotionView model (Altair 2026.1).

Reads the hardpoint CSV and creates, for all four corners:

- the 10 hardpoints per corner, as MotionView ``Point`` entities;
- one ``Body`` per moving part (UCA, LCA, tie rod, upright, wheel);
- ``Cylinder`` graphics spanning the hardpoints, so each member is visible.

Run it from MotionView's Python console (the Jupyter QtConsole with the ``hwx``
profile), with a model open::

    p = r"c:\\soft\\FSAE\\Suspension and Vehicle Dynamics\\altair_model\\suspension.py"
    exec(open(p).read())

Re-running is safe: entities are matched by name and updated in place, so
pushing a revised CSV into an open model does not duplicate anything.

Scope: geometry only. No joints are created, and mass/inertia are left at
MotionView's placeholder defaults -- the model is *not* solver-ready as it
stands. Add the joints and real inertias before handing it to MotionSolve.

Units: MMKS (mm, kg, s, N). The script refuses to run if the model's length
unit is not millimetres rather than silently misplacing every point.
Frame: ISO 8855 -- X+ forward, Y+ LEFT, Z+ up, origin at the front axle
centreline on the ground plane. This is the CSV's native frame, so the
coordinates go in untransformed.
"""

import csv
from pathlib import Path

# `Link` does not exist in this API -- a member is a Body carrying Cylinder
# graphics. Every entity constructor takes its parent System as the first
# positional argument; entities built without one are parented to a detached
# ROOT singleton and never appear in the model.
from hw.mview.mbd import Body, Cylinder, Model, Point

# `exec(open(...).read())` leaves `__file__` undefined, so fall back to the
# checked-out location. Pass `csv_path=` to create_suspension_geometry() to
# override either way.
_FALLBACK = r"c:\soft\FSAE\Suspension and Vehicle Dynamics\altair_model\suspension.py"
HERE = Path(globals().get("__file__", _FALLBACK)).resolve().parent

# The merged set is the current design, regenerated by scripts/geometry_summary.py
# from sla_geometry.py + steering_geometry.py. legacy_app/carro_formula_2027.csv
# is the app's copy of the same numbers and currently matches it point for point.
DEFAULT_CSV = HERE.parent / "Geometry Summary" / "hardpoints_2027_merged.csv"

CORNERS = ("FL", "FR", "RL", "RR")

POINT_NAMES = (
    "UCA_IN_FRONT",
    "UCA_IN_REAR",
    "UCA_OUT",
    "LCA_IN_FRONT",
    "LCA_IN_REAR",
    "LCA_OUT",
    "TIE_ROD_IN",
    "TIE_ROD_OUT",
    "WHEEL_CENTER",
    "CONTACT_PATCH",
)

# One body per moving part, drawn as cylinders spanning pairs of hardpoints.
# A wishbone is two legs meeting at its outer ball joint, so it takes two
# segments on one body.
LINKS = (
    ("uca", "UCA", (
        ("UCA_IN_FRONT", "UCA_OUT", "front leg"),
        ("UCA_IN_REAR", "UCA_OUT", "rear leg"),
    )),
    ("lca", "LCA", (
        ("LCA_IN_FRONT", "LCA_OUT", "front leg"),
        ("LCA_IN_REAR", "LCA_OUT", "rear leg"),
    )),
    ("tierod", "Tie Rod", (
        ("TIE_ROD_IN", "TIE_ROD_OUT", "rod"),
    )),
    ("upright", "Upright", (
        ("LCA_OUT", "UCA_OUT", "kingpin axis"),
        ("LCA_OUT", "WHEEL_CENTER", "lower spindle arm"),
        ("UCA_OUT", "WHEEL_CENTER", "upper spindle arm"),
        ("LCA_OUT", "TIE_ROD_OUT", "steering arm"),
    )),
    ("wheel", "Wheel", (
        # Drawn from the CSV's two wheel points, so its lean *is* the static
        # camber. It is a graphic on its own body, not a spinning wheel: no
        # revolute joint is created here.
        ("WHEEL_CENTER", "CONTACT_PATCH", "loaded radius"),
    )),
)


def load_hardpoints(csv_path):
    """Read the hardpoint CSV. Return dict: (corner, point_name) -> (x, y, z) in mm.

    Raises ValueError on a malformed file or an incomplete corner, so a partial
    model is never built from partial data.
    """
    csv_path = Path(csv_path)
    if not csv_path.is_file():
        raise FileNotFoundError(f"hardpoint CSV not found: {csv_path}")

    hardpoints = {}
    # utf-8-sig: Excel writes a BOM, which would otherwise corrupt the first
    # column name and make every row lookup fail.
    with open(csv_path, newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        wanted = ("corner", "point", "x_mm", "y_mm", "z_mm")
        absent = [column for column in wanted if column not in (reader.fieldnames or ())]
        if absent:
            raise ValueError(f"{csv_path.name}: missing column(s) {', '.join(absent)}")

        for line, row in enumerate(reader, start=2):
            key = (row["corner"].strip().upper(), row["point"].strip().upper())
            try:
                hardpoints[key] = (
                    float(row["x_mm"]),
                    float(row["y_mm"]),
                    float(row["z_mm"]),
                )
            except (TypeError, ValueError) as exc:
                raise ValueError(f"{csv_path.name} line {line}: bad coordinate ({exc})") from exc

    missing = [
        f"{corner}/{name}"
        for corner in CORNERS
        for name in POINT_NAMES
        if (corner, name) not in hardpoints
    ]
    if missing:
        raise ValueError(f"{csv_path.name}: missing hardpoint(s): {', '.join(missing)}")

    return hardpoints


def _require_millimetres(model):
    """Refuse to place mm coordinates into a model that is not working in mm."""
    units = getattr(model, "units", None)
    length = getattr(units, "length", None)
    if length is not None and length != "MILLIMETER":
        raise ValueError(
            f"model length unit is {length}, expected MILLIMETER -- the CSV is in mm. "
            "Set the model units to MMKS, or convert the hardpoints first."
        )


def _point(model, name, label, xyz):
    """Create the point, or move an existing one of that name onto the CSV value."""
    existing = model.getChild(name=name)
    if existing is not None:
        existing.x, existing.y, existing.z = xyz
        return existing, False
    x, y, z = xyz
    return Point(model, name=name, label=label, x=x, y=y, z=z), True


def _body(model, name, label):
    """Create the body, or reuse the existing one of that name.

    Mass and inertia are left at MotionView's placeholder defaults; the team has
    no mass data for these parts yet, and inventing numbers here would put
    fabricated inertias into a model someone may later solve.
    """
    existing = model.getChild(name=name)
    if existing is not None:
        return existing, False
    return Body(model, name=name, label=label), True


def _segment(model, name, label, body, start, end, radius_mm):
    """Draw a capped cylinder from `start` to `end`, owned by `body`.

    `useautolen` makes MotionView size the cylinder to reach the align point,
    so the graphic tracks the hardpoints instead of holding a stale length.
    """
    existing = model.getChild(name=name)
    if existing is not None:
        existing.body = body
        existing.r1 = radius_mm
        existing.align(start, end)  # sets origin, align_meth1='Point', useautolen
        return existing, False

    cylinder = Cylinder(
        model,
        name=name,
        label=label,
        body=body,
        origin=start,
        align_meth1="Point",
        align_pt1=end,
        useautolen=True,
        r1=radius_mm,
        cap_flag="CAPBOTH",
    )
    return cylinder, True


def create_suspension_geometry(csv_path=None, radius_mm=6.0, model=None):
    """Build (or refresh) the four suspension corners in the current model.

    Args:
        csv_path: hardpoint CSV; defaults to the merged 2027 set.
        radius_mm: cylinder radius used for every member graphic -- cosmetic
            only, it carries no structural meaning.
        model: target model; defaults to the current one, created if needed.

    Returns:
        The model that was populated.
    """
    model = model if model is not None else Model.getCurrentModel(create=True)
    _require_millimetres(model)

    csv_path = Path(csv_path) if csv_path is not None else DEFAULT_CSV
    hardpoints = load_hardpoints(csv_path)

    points = {}
    created = updated = 0

    for corner in CORNERS:
        for name in POINT_NAMES:
            point, is_new = _point(
                model,
                name=f"p_{corner.lower()}_{name.lower()}",
                label=f"{corner} {name}",
                xyz=hardpoints[(corner, name)],
            )
            points[(corner, name)] = point
            created, updated = (created + 1, updated) if is_new else (created, updated + 1)

    for corner in CORNERS:
        for key, part_label, segments in LINKS:
            body, is_new = _body(
                model,
                name=f"b_{corner.lower()}_{key}",
                label=f"{corner} {part_label}",
            )
            created, updated = (created + 1, updated) if is_new else (created, updated + 1)

            for index, (start, end, segment_label) in enumerate(segments):
                _, is_new = _segment(
                    model,
                    name=f"gcyl_{corner.lower()}_{key}_{index}",
                    label=f"{corner} {part_label} - {segment_label}",
                    body=body,
                    start=points[(corner, start)],
                    end=points[(corner, end)],
                    radius_mm=radius_mm,
                )
                created, updated = (created + 1, updated) if is_new else (created, updated + 1)

    print(f"Hardpoints read from {csv_path}")
    print(f"Created {created} entit(ies), updated {updated} in place.")
    print(f"Model now has {len(model.points())} point(s).")
    print("Geometry only -- no joints, no real inertias. Not solver-ready yet.")
    return model


if __name__ == "__main__":
    create_suspension_geometry()
